### ISSUE TITLE
Migrate to dedicated database

### ISSUE THREAD

**Issue by arnenator** [devops2024-group-e/itu-minitwit#157]
# What is it this about?
As part of this weeks tasks we need to create a dedicated database server. What we would have to do here is to do the following:

### Tasks
- [x] Create a database in digitalocean
- [ ] Change password for the admin
- [ ] Create a user for the application 
- [ ] (Implement code to handle double database for a limited time)
- [ ] Get SQL dump of the current database and insert it into the new
- [ ] Decomission the old database
- [ ] Remove database image from the docker-compose file
