### ISSUE TITLE
Make file to config management server called do_ssh_key

### ISSUE THREAD

**Issue by Pinkvinus** [devops2024-group-e/itu-minitwit#181]
The management server needs an ssh key

### Tasks
- [x] Generate new ssh key pair for the conf server
   - [x] Save private so that it can be used when provisioning the server
   - [x] Add public key to digitalocean
- [ ] Set environment variable `DIGITAL_OCEAN_SSH_KEY_NAME` from conf Vagrant file so that the conf server has this registered
