### ISSUE TITLE
Add at least three linters

### ISSUE THREAD

**Issue by arnenator** [devops2024-group-e/itu-minitwit#193]
### Tasks
- [x] Linter for docker - Use Hadolint
- [x] Linter for C# - Use [dotnet-format](https://github.com/dotnet/format)
- [x] Code formatter for C# - Use [dotnet-format](https://github.com/dotnet/format)
- [x] (Linter for YAML)
- [x] Add precommit to github action workflow

**Comment by arnenator** [comment]
We are at the moment a bit angry at Vagrant. So we are going to have a technical discussion before actually spending more time in enhancing the vagrant setup.
