### ISSUE TITLE
Add scaling to the project

### ISSUE THREAD

**Issue by Pinkvinus** [devops2024-group-e/itu-minitwit#213]
Do either of the following:

1. Create a high-availability setup with a hot and standby server for your ITU-MiniTwit application. In such a setup you would have two replica of your application server where only one is ever active at a time, i.e., no load balancer in front of either of them. The setup should resemble [the one discussed in the lecture](https://www.digitalocean.com/community/tutorials/how-to-set-up-highly-available-web-servers-with-keepalived-and-floating-ips-on-ubuntu-14-04).

Or:

2. Create a Docker Swarm cluster for your ITU-MiniTwit applications in which various components run as services and can be scaled as needed. Note, very likely you do not want to scale you DB servers horizontally (to keep your data consistent) but only all the services 'in front' of it.

### Tasks
- [ ] #226
- [ ] #227
- [x] #228

**Comment by Pinkvinus** [comment]
- [ ] set up manager node
- [ ] Add installations to ansible -> docker, docker swarm
- [ ] add worker nodes to the swarm
- [ ] add the manager node to the github workflow
