### ISSUE TITLE
Add scaling to frontend 👬

### ISSUE THREAD

**Issue by amalieboegild** [devops2024-group-e/itu-minitwit#238]
# What is this about?
This issue is about adding more replicas for the frontend on our new docker swarm. This seems like a simple task, "we just add 2 instead of 1 in the docker-compose.yaml". But, it is not that simple. We use a session to store the current users userid. This session is saved in memory on the frontend instance, meaning this will be lost when routed to another frontend container instance. 

# How can this be solved?
We can add a distributed session cache. Dotnet has a library to do so it is just a matter of implementing it. I am not sure if we can use our existing database cluster, but that is something that you can check.

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-8.0
https://www.nuget.org/packages/Community.Microsoft.Extensions.Caching.PostgreSql

### Tasks
- [ ] Create a new table for sessions in our minitwit database cluster through pulumi
- [ ] Add code to handle distributed sessions
- [ ] Increase the replicas of the frontend

**Comment by amalieboegild** [comment]
We tried and failed
