### ISSUE TITLE
Add frontend to service discovery in order to get frontend metrics

### ISSUE THREAD

**Issue by amalieboegild** [devops2024-group-e/itu-minitwit#239]
# What is this issue about?
Since it took a long time to add the backend api to the metrics board, then we didn't have time to add the frontend. However, we need to do that now. This time, however, is going to be easier. This is a simple copy-paste and adjust task.

### Tasks
- [ ] Go into `.infrastructure/servers/swm-server/prometheus.yaml` and copy the scrape config and paste it again in the same file
- [ ] Change the name from `minitwit-api` to `minitwit-frontend`
- [ ] Only include `minitwit-frontend` applications
- [ ] Deploy and check at [this url](http://165.232.73.220:9090/targets?search=) that the new target is up and running

**Comment by amalieboegild** [comment]
Solved by #243
