### ISSUE TITLE
Upgrade our applications to dotnet 8 👍

### ISSUE THREAD

**Issue by Myssenberg** [devops2024-group-e/itu-minitwit#250]
# What is this about?
We use an LTS version of dotnet, which is cool. But since we do not have a complicated application, we should just follow the updates of dotnet versions. It is good practice to upgrade the version of your application and it should be a trivial task, else we are doing something wrong.

### Tasks
- [x] Change the dotnet version numbers of our applications
    - [x] Minitwit
    - [x] Minitwit.Tests
    - [x] MinitwitSimulatorApi
    - [x] Minitwit.Infrastructure
    - [x] Minitwit.Infrastructure.Tests
    - [x] Minitwit.Simulator.Api.Tests
- [x] Change the dotnet version in the docker images
