### ISSUE TITLE
Implement API for the simulator

### ISSUE THREAD

**Issue by sarahcecilie** [devops2024-group-e/itu-minitwit#45]
### Tasks
- [x] Create the same end points
- [x] Copy same logic from `Minitwit` to the new API
- [ ] Make sure that the test passes from Helge
