### ISSUE TITLE
Add singular API methods to API simulator

### ISSUE THREAD

**Issue by sarahcecilie** [devops2024-group-e/itu-minitwit#52]
### Tasks
- [x] Add singular getMessages method to [TimelineController.cs](https://github.com/devops2024-group-e/itu-minitwit/blob/feature/basic-api-install/MinitwitSimulatorAPI/Controllers/TimelineController.cs)
- [x] Add singular getAllMessages method to [TimelineController.cs](https://github.com/devops2024-group-e/itu-minitwit/blob/feature/basic-api-install/MinitwitSimulatorAPI/Controllers/TimelineController.cs)
- [x] Add singular getFollowers method to [TimelineController.cs](https://github.com/devops2024-group-e/itu-minitwit/blob/feature/basic-api-install/MinitwitSimulatorAPI/Controllers/TimelineController.cs)

The methods that should be implemented can be seen in the [API_specs](https://github.com/itu-devops/lecture_notes/blob/master/sessions/session_03/API_Spec/minitwit_sim_api.py)

Co-authored-by: Mille Loo <mille.mei.zhen.loo@gmail.com>

**Comment by sarahcecilie** [comment]
@Arneproductions It's worked into the 'Implement API for the simulator' issue, so I mistakenly moved this to 'To be reviewed'. I will move it to 'Done' instead.
