### ISSUE TITLE
Use Async and Await in Controllers and other places in the code 🧵 

### ISSUE THREAD

**Issue by arnenator** [devops2024-group-e/itu-minitwit#93]
# What is the issue we are trying to solve?
At the moment we have only recieved one type of failure i.e. `ReadTimeout`. A quick search on google told us that this is the error from client side(the simulator) which says that the server took too long to provide a response... or something like that. 
At the moment we have to wait for the database to return our SQL queries. This can have an effect when we try to process multiple request at one time.

## What should we do then?
We should use async and await. This is a language feature in C# that lets us handle a piece of code asynchronously and define that at this point we need to wait to give the cpu time to someone else. 

There is some material here that you can look at to get a feeling what it is: https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/async-scenarios

And I have a previous example of how an async and await api controller looks like:
https://github.com/BDSA-2021/BDSA21-Say-AAAAAA/blob/eb0464558159b6ef824ef5e2370ba4accd4db11b/SELearning.API/Controllers/SectionController.cs#L28-L41

### Tasks
- [ ] Use Async and await in controllers
    - [ ] Refactor to use it in `TimelineController`
    - [ ] Refactor to use it in `LatestController`
    - [ ] Refactor to use it in `LoginController`
    - [ ] Refactor to use it in `LogoutController`
    - [ ] Refactor to use it in `RegisterController`
- [ ] Use Async and await in all Repositories
